export enum PeThemesRequestsErrorsEnum {
  CreateApplicationTheme = 'builder-themes.apm_errors.create_application_theme',
  CreateThemeAlbum = 'builder-themes.apm_errors.create_theme_album',
  DeleteTemplateTheme = 'builder-themes.apm_errors.delete_template_theme',
  DeleteThemeAlbum = 'builder-themes.apm_errors.delete_theme_album',
  DuplicateTemplateTheme = 'builder-themes.apm_errors.duplicate_template_theme',
  DuplicateThemeAlbum = 'builder-themes.apm_errors.duplicate_theme_album',
  GetTemplateItemThemes = 'builder-themes.apm_errors.get_template_item_themes',
  GetTemplateList = 'builder-themes.apm_errors.get_template_list',
  GetTemplateThemes = 'builder-themes.apm_errors.get_template_themes',
  GetThemeAlbumByAncestor = 'builder-themes.apm_errors.get_theme_album_by_ancestor',
  GetThemeAlbumById = 'builder-themes.apm_errors.get_theme_album_by_id',
  GetThemeAlbumByParent = 'builder-themes.apm_errors.get_theme_album_by_parent',
  GetThemeBaseAlbum = 'builder-themes.apm_errors.get_theme_base_album',
  GetThemeByAlbum = 'builder-themes.apm_errors.get_theme_by_album',
  GetThemeById = 'builder-themes.apm_errors.get_theme_by_id',
  GetThemesByTemplateId = 'builder-themes.apm_errors.get_themes_by_template_id',
  GetThemesList = 'builder-themes.apm_errors.get_themes_list',
  InstantInstallTemplateTheme = 'builder-themes.apm_errors.instant_install_template_theme',
  InstallTemplateTheme = 'builder-themes.apm_errors.install_template_theme',
  LinkThemeToAlbum = 'builder-themes.apm_errors.link_theme_to_album',
  SwitchTemplateTheme = 'builder-themes.apm_errors.switch_template_theme',
  UnlinkTheme = 'builder-themes.apm_errors.unlink_theme',
  UpdateTheme = 'builder-themes.apm_errors.update_theme',
  UpdateThemeAlbum = 'builder-themes.apm_errors.update_theme_album',
}
