export enum PeMessageWebSocketEvents {
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  UNAUTHORIZED = 'unauthorized',
  AUTHENTICATED = 'authenticated',

  INITIAL_APP_CHANNELS_CREATED = 'messages.ws-client.events.initial-app-channels-created',
  MESSAGE_POSTED = 'messages.ws-client.message.posted',
  MESSAGE_PINNED = 'messages.ws-client.message.pinned',
  MESSAGE_UNPINNED = 'messages.ws-client.message.unpinned',
  MESSAGE_UPDATED = 'messages.ws-client.message.updated',
  MESSAGE_DELETED = 'messages.ws-client.message.deleted',
  MESSAGE_TYPING = 'messages.ws-client.chat.typing-members-updated',
  MESSAGE_ONLINE = 'messages.ws-client.chat.online-members-updated',
  MESSAGE_LEAVE = 'messages.ws-client.chat-room.leave',
  CHAT_CREATED = 'messages.ws-client.chat.created',
  CHAT_UPDATED = 'messages.ws-client.chat.updated',
  CHAT_DELETED = 'messages.ws-client.chat.deleted',
  CHAT_MEMBER_CHANGED = 'messages.ws-client.chat.member.changed',
  CHAT_MEMBER_INCLUDED = 'messages.ws-client.chat.member.included',
  CHAT_MEMBER_EXCLUDED = 'messages.ws-client.chat.member.excluded',
  CHAT_MEMBER_LEAVE = 'messages.ws-client.chat.leave-member',
  CONTACT_CREATED = 'messages.ws-client.contact.created',
  CONTACT_UPDATED = 'messages.ws-client.contact.updated',
  ROOM_JOINED = 'messages.ws-client.room.joined',

  EMIT_BUSINESS_ROOM_JOIN = 'messages.ws-client.business-room.join',
  EMIT_CHAT_ROOM_JOIN = 'messages.ws-client.chat-room.join',
  EMIT_MESSAGE_DELETE = 'messages.ws-client.message.delete',
  EMIT_MESSAGE_SEND = 'messages.ws-client.message.send',
  EMIT_MESSAGE_SCROLL_REQUEST = 'messages.ws-client.message.scroll.request',
  MESSAGE_SCROLL_RESPONSE = 'messages.ws-client.scroll.response',
  EMIT_MESSAGE_UPDATE = 'messages.ws-client.message.update',
  EMIT_MESSAGE_FORWARD = 'messages.ws-client.message.forward',
  EMIT_MESSAGE_MARK_READ = 'messages.ws-client.message.mark-read',
  EMIT_MESSAGE_PIN = 'messages.ws-client.message.pin',
  EMIT_MESSAGE_UNPIN = 'messages.ws-client.message.unpin',
  EMIT_MESSAGE_TYPING = 'messages.ws-client.chat-room.typing',
  EMIT_MESSAGE_TYPING_STOPPED = 'messages.ws-client.chat-room.typing-stopped',
}
