export * from './editor-channels-section/editor-channels-section.component';
export * from './editor-category-section/editor-category-section.component';
export * from './editor-inventory-section/editor-inventory-section.component';
export * from './editor-main-section/editor-main-section.component';
export * from './editor-taxes-section/editor-taxes-section.component';
export * from './editor-variants-section/editor-variants-section.component';
export * from '../variant-editor/variant-editor.component';
export * from './editor-visibility-section/editor-visibility-section.component';
export * from './editor-recurring-billing-section/editor-recurring-billing-section.component';
export * from './editor-shipping-section/editor-shipping-section.component';
export * from './editor-content-section/editor-content-section.component';
export * from './editor-recommendations-section/editor-recommendations-section.component';
export * from './editor-attributes-section/editor-attributes-section.component'
export * from './editor-pricing-section/editor-pricing-section.component'
export * from './editor-seo-section/editor-seo-section.component'
