export enum Icons {
  'close' = '/assets/icons/small-close-icon.svg',
  'edit' = '/assets/icons/edit.svg',
  'history' = '/assets/icons/history.png',
  'inspector' = '/assets/icons/inspector.svg',
  'language-chinese' = '/assets/icons/language-chinese.png',
  'language-english' = '/assets/icons/language-english.png',
  'language-german' = '/assets/icons/language-german.png',
  'language-italian' = '/assets/icons/language-italian.png',
  'language-spanish' = '/assets/icons/language-spanish.png',
  'language' = '/assets/icons/language.svg',
  'layer-list' = '/assets/icons/layer-list.svg',
  'manage-languages' = '/assets/icons/manage-languages.svg',
  'master-pages' = '/assets/icons/master-pages.svg',
  'navigator' = '/assets/icons/navigator.svg',
  'sidebar-navigator' = '/assets/icons/sidebar-navigator.svg',
  'preview' = '/assets/icons/preview.png',
  'scripts' = '/assets/icons/scripts.svg',
  'seo' = '/assets/icons/seo.svg',
  'settings' = '/assets/icons/settings.svg',
  'theme' = '/assets/icons/theme.svg',
}
