import { AppType } from '@pe/common';

const apis = {
  config: {
    appType: AppType.Pos,
    clarityId: '',
    env: 'test',
    fullStoryOrgId: '4SJ8V',
    googleMapsApiKey: 'AIzaSyDB-7kzuFYxb8resf60yF21TKUkTbGhljc',
    recaptchaSiteKey: '6LfM-MoUAAAAAAAkGf2jpnz3tfqz7EtKv2OkDMU0',
    tmetrixOrigId: 'cx8xec1a',
  },
  custom: {
    cdn: 'https://cdn.test.devpayever.com',
    checkoutCdn: '',
    elasticUrl: 'https://91c12366dc634bb0a9a03bec07d21204.apm.westeurope.azure.elastic-cloud.com:443',
    googleMaps: '',
    i18n: 'https://translation-backend.test.devpayever.com',
    integrator: 'https://integrator.devpayever.com',
    proxy: 'https://proxy.test.devpayever.com',
    storage: 'https://payevertesting.blob.core.windows.net',
    translation: 'https://payevertesting.azureedge.net',
    translationCdn: '',
    widgetsCdn: 'https://widgets.test.devpayever.com',
  },
  primary: {
    affiliates: 'https://test.payever.affiliates',
    affiliatesHost: 'test.payever.affiliates',
    blog: 'https://test.payever.blog',
    blogHost: 'test.payever.blog',
    business: 'https://test.payever.business',
    businessHost: 'test.payever.business',
    email: '',
    emailHost: 'test.payever.email',
    invoice: 'https://test.payever.invoice',
    invoiceHost: 'test.payever.invoice',
    mail: 'https://test.payever.email',
    main: 'https://test.devpayever.com',
    mainHost: 'test.devpayever.com',
    pos: 'https://test.payever.business',
    posHost: 'test.payever.business',
    shop: 'https://test.devpayever.shop',
    shopHost: 'test.devpayever.shop',
    shopHostNew: '',
    site: 'https://test.payever.site',
    siteHost: 'test.payever.site',
    subscription: 'https://test.payever.page',
    subscriptionHost: 'test.payever.page',
  },
  php: {
    checkout: 'https://checkout-php.test.devpayever.com',
    financeExpress: 'https://finance-express-php.test.devpayever.com',
    translation: 'https://translation-backend.test.devpayever.com',
  },
  connect: {
    dandomain: 'https://dandomain-backend.test.devpayever.com',
    debitoor: '',
    dhl: 'https://dhl-backend.test.devpayever.com',
    facebook: 'https://facebook-backend.test.devpayever.com',
    facebookMessenger: 'https://facebook-messenger-backend.test.devpayever.com',
    googleShopping: 'https://google-shopping-backend.test.devpayever.com',
    instagram: 'https://instagram-backend.test.devpayever.com',
    livechat: 'https://livechat-backend.test.devpayever.com',
    qr: 'https://qr-backend.test.devpayever.com',
    shopify: 'https://shopify-backend.test.devpayever.com',
    twilio: 'https://twilio-connect.test.devpayever.com',
    whatsapp: 'https://whatsapp-backend.test.devpayever.com',
  },
  backend: {
    affiliates: 'https://affiliates-backend.test.devpayever.com',
    appointments: '',
    appRegistry: 'https://app-registry.test.devpayever.com',
    auth: 'https://auth.test.devpayever.com',
    billingSubscription: 'https://billing-subscription-backend.test.devpayever.com',
    blog: 'https://blog-backend.test.devpayever.com',
    blogs: '',
    builder: 'https://builder.test.devpayever.com',
    builderAffiliate: 'https://builder-affiliate.test.devpayever.com',
    builderAffiliateWs: 'wss://builder-affiliate.test.devpayever.com/ws',
    builderAppointments: '',
    builderBlog: 'https://builder-blogs.test.devpayever.com',
    builderBlogWs: 'wss://builder-blogs.test.devpayever.com/ws',
    builderGenerator: 'https://builder-generator.test.devpayever.com',
    builderInvoice: 'https://builder-invoice.test.devpayever.com',
    builderInvoiceWs: 'wss://builder-invoice.test.devpayever.com/ws',
    builderMail: '',
    builderMailWs: '',
    builderMedia: 'https://builder-media.test.devpayever.com',
    builderPos: 'https://builder-pos.test.devpayever.com',
    builderPosWs: 'wss://builder-pos.test.devpayever.com/ws',
    builderShop: 'https://builder-shops.test.devpayever.com',
    builderShopWs: 'wss://builder-shops.test.devpayever.com/ws',
    builderSite: 'https://builder-site.test.devpayever.com',
    builderSiteWs: 'wss://builder-site.test.devpayever.com/ws',
    builderSubscription: 'https://builder-subscription.test.devpayever.com',
    builderSubscriptionWs: 'wss://builder-subscription.test.devpayever.com/ws',
    channels: 'https://channels-backend.test.devpayever.com',
    checkout: 'https://checkout-backend.test.devpayever.com',
    checkoutAnalytics: 'https://checkout-analytics-backend.test.devpayever.com',
    commerceos: 'https://commerceos-backend.test.devpayever.com',
    common: 'https://common-backend.test.devpayever.com',
    connect: 'https://connect-backend.test.devpayever.com',
    contacts: 'https://contacts-backend.test.devpayever.com',
    coupons: 'https://coupons-backend.test.devpayever.com',
    devicePayments: 'https://device-payments-backend.test.devpayever.com',
    errorNotifications: 'https://error-notifications-backend.test.devpayever.com',
    financeExpress: 'https://finance-express-backend.test.devpayever.com',
    inventory: 'https://inventory-backend.test.devpayever.com',
    invoice: 'https://invoice-backend.test.devpayever.com',
    livechat: '',
    mailer: 'https://mailer.test.devpayever.com',
    mailerReport: 'https://mailer-report-backend.test.devpayever.com',
    marketing: 'https://marketing-backend.test.devpayever.com',
    media: 'https://media.test.devpayever.com',
    message: 'https://message-backend.test.devpayever.com',
    notifications: 'https://notifications-backend.test.devpayever.com',
    notificationsWs: 'wss://notifications-backend.test.devpayever.com/ws',
    payments: 'https://checkout-php.test.devpayever.com',
    paymentDataStorage: 'https://payment-data-storage-backend.test.devpayever.com',
    paymentNotifications: 'https://payment-notifications-backend.test.devpayever.com',
    plugins: 'https://plugins-backend.test.devpayever.com',
    pos: 'https://pos-backend.test.devpayever.com',
    products: 'https://products-backend.test.devpayever.com',
    shipping: 'https://shipping-backend.test.devpayever.com',
    shop: 'https://shop-backend.test.devpayever.com',
    shops: '',
    site: 'https://site-backend.test.devpayever.com',
    siteWs: 'wss://site-backend.test.devpayever.com/ws',
    social: '',
    spotlight: '',
    statistics: 'https://statistics-backend.test.devpayever.com',
    statisticsWs: 'wss://statistics-backend.test.devpayever.com/ws',
    studio: 'https://studio-backend.test.devpayever.com',
    studioWs: 'wss://studio-backend.test.devpayever.com/ws',
    synchronizer: 'https://synchronizer-backend.test.devpayever.com',
    thirdParty: 'https://third-party.test.devpayever.com',
    transactions: 'https://transactions-backend.test.devpayever.com',
    transactionsWs: 'wss://transactions-backend.test.devpayever.com/ws',
    users: 'https://users.test.devpayever.com',
    wallpapers: 'https://wallpapers-backend.test.devpayever.com',
    webWidgets: 'https://web-widgets-backend.test.devpayever.com',
    widgets: 'https://widgets-backend.test.devpayever.com',
    widgetsWs: 'wss://widgets-backend.test.devpayever.com/ws',
  },
  frontend: {
    affiliates: 'https://affiliates-frontend.test.devpayever.com',
    affiliatesClient: '',
    blogs: '',
    blogsClient: '',
    builder: 'https://builder-frontend.test.devpayever.com',
    builderAffiliatesClient: 'https://builder-affiliates-client-frontend.test.devpayever.com',
    builderBlogClient: 'https://builder-blog-client-frontend.test.devpayever.com',
    builderClient: 'https://builder-client-frontend.test.devpayever.com',
    builderPosClient: 'https://builder-pos-client-frontend.test.devpayever.com',
    builderShopClient: 'https://builder-shop-client-frontend.test.devpayever.com',
    builderSubscriptionsClient: 'https://builder-subscriptions-client-frontend.test.devpayever.com',
    builderTranslate: '',
    cart: 'https://cart-frontend.test.devpayever.com',
    checkout: 'https://checkout-frontend.test.devpayever.com',
    checkoutWrapper: 'https://checkout.test.devpayever.com',
    commerceos: 'https://commerceos.test.devpayever.com',
    connect: 'https://connect-frontend.test.devpayever.com',
    contacts: 'https://contacts-frontend.test.devpayever.com',
    marketing: 'https://marketing-frontend.test.devpayever.com',
    paymentOptionsInstantPayment: 'https://payment-instant-payment-frontend.test.devpayever.com',
    paymentOptionsPayex: 'https://payment-payex-frontend.test.devpayever.com',
    paymentOptionsPaypal: 'https://payment-paypal-frontend.test.devpayever.com',
    paymentOptionsSantanderAt: 'https://payment-santander-at-frontend.test.devpayever.com',
    paymentOptionsSantanderDe: 'https://payment-santander-de-frontend.test.devpayever.com',
    paymentOptionsSantanderDeCcp: 'https://payment-santander-de-ccp-frontend.test.devpayever.com',
    paymentOptionsSantanderDeFact: 'https://payment-santander-de-fact-frontend.test.devpayever.com',
    paymentOptionsSantanderDeInvoice: 'https://payment-santander-de-invoice-frontend.test.devpayever.com',
    paymentOptionsSantanderDk: 'https://payment-santander-dk-frontend.test.devpayever.com',
    paymentOptionsSantanderNl: 'https://payment-santander-nl-frontend.test.devpayever.com',
    paymentOptionsSantanderNo: 'https://payment-santander-no-frontend.test.devpayever.com',
    paymentOptionsSantanderNoInvoice: 'https://payment-santander-no-invoice-frontend.test.devpayever.com',
    paymentOptionsSantanderSe: 'https://payment-santander-se-frontend.test.devpayever.com',
    paymentOptionsSofort: 'https://payment-sofort-frontend.test.devpayever.com',
    paymentOptionsStripe: 'https://payment-stripe-frontend.test.devpayever.com',
    paymentOptionsSwedbank: 'https://payment-swedbank-frontend.test.devpayever.com',
    paymentOptionsWiretransfer: 'https://payment-wiretransfer-frontend.test.devpayever.com',
    pos: 'https://pos-frontend.test.devpayever.com',
    posClient: '',
    products: 'https://products-frontend.test.devpayever.com',
    settings: 'https://settings.test.devpayever.com',
    shipping: 'https://shipping-frontend.test.devpayever.com',
    shops: '',
    shopsClient: '',
    subscriptions: 'https://subscriptions-frontend.test.devpayever.com',
    subscriptionsClient: '',
    transactions: 'https://transactions-frontend.test.devpayever.com',
  },
  thirdParty: {
    communications: 'https://communications-third-party.test.devpayever.com',
    messenger: 'https://messenger-third-party.test.devpayever.com',
    payments: 'https://payments-third-party.test.devpayever.com',
    plugins: 'https://plugins-third-party.test.devpayever.com',
    products: 'https://products-third-party.test.devpayever.com',
    shipping: 'https://shipping-third-party.test.devpayever.com',
  },
  payments: {
    applePay: 'https://apple-pay-payments.test.devpayever.com',
    instantPayment: 'https://instant-payment-payments.test.devpayever.com',
    paypal: 'https://paypal-payments.test.devpayever.com',
    santanderAt: 'https://santander-at-payments.test.devpayever.com',
    santanderDeFactoring: 'https://santander-de-factoring-payments.test.devpayever.com',
    santanderDeInvoice: 'https://santander-de-invoice-payments.test.devpayever.com',
    santanderNl: 'https://santander-nl-payments.test.devpayever.com',
    sofort: 'https://sofort-payments.test.devpayever.com',
    stripe: 'https://stripe-payments.test.devpayever.com',
    stripeDirectDebit: 'https://stripe-directdebit-payments.test.devpayever.com',
    swedbank: 'https://swedbank-payments.test.devpayever.com',
  },
};

export const environment = {
  apis,
  // appType: AppType.Affiliates,
  // defaultDomain: 'affille',
  // appType: AppType.Shop,
  // defaultDomain: 'some-busoness-8-4',
  // appType: AppType.Shop,
  // defaultDomain: 'wewe',
  defaultDomain: '123123123-j0vq',
  // defaultDomain: 'invoice200',
  production: false,
};
