export enum TimeZones {
  GMT = 'Etc/GMT',
  GMT0 = 'Etc/GMT+0',
  GMT1 = 'Etc/GMT+1',
  GMT2 = 'Etc/GMT+2',
  GMT3 = 'Etc/GMT+3',
  GMT4 = 'Etc/GMT+4',
  GMT5 = 'Etc/GMT+5',
  GMT6 = 'Etc/GMT+6',
  GMT7 = 'Etc/GMT+7',
  GMT8 = 'Etc/GMT+8',
  GMT9 = 'Etc/GMT+9',
  GMT10 = 'Etc/GMT+10',
  GMT11 = 'Etc/GMT+11',
  GMT12 = 'Etc/GMT+12',
  GMTm1 = 'Etc/GMT-1',
  GMTm2 = 'Etc/GMT-2',
  GMTm3 = 'Etc/GMT-3',
  GMTm4 = 'Etc/GMT-4',
  GMTm5 = 'Etc/GMT-5',
  GMTm6 = 'Etc/GMT-6',
  GMTm7 = 'Etc/GMT-7',
  GMTm8 = 'Etc/GMT-8',
  GMTm9 = 'Etc/GMT-9',
  GMTm10 = 'Etc/GMT-10',
  GMTm11 = 'Etc/GMT-11',
  GMTm12 = 'Etc/GMT-12',
}
export enum WeekDay {
  Monday = 'monday',
  Tuesday = 'tuesday',
  Wednesday = 'wednesday',
  Thursday = 'thursday',
  Friday = 'friday',
  Saturday = 'saturday',
  Sunday = 'sunday',
}
