export enum FormFieldTypeEnum {
  Text = 'text',
  Textarea = 'textarea',
  Date = 'date',
  Number = 'number',
  Boolean = 'boolean',
  Password = 'password',
  Select = 'select',
  Toggle = 'toggle',
  Checkbox = 'checkbox',
  Phone = 'phone',
  SelectBusinessStatus = 'select_business_status',
  SelectStatus = 'select_status',
  SelectSales = 'select_sales',
  AutocompleteIndustry = 'autocomplete_industry',
  Hidden = 'hidden',
  SelectPhoneCode = 'select_phone_code',
}
