export const KEY = `-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGt0znWTu3Uh+EDpdMbEXjR0ekRX
4Jr0/fwXEo8VbjLNk+Xqp7lhipePq84KVwRON6hbxrWn02kCLBOBV5LB3YbSmbqX
xFoTe4p4a7g3ZDgRnTYSo3ZDxQSQohjYzhdOdXLD6+qdWiV9JLdvu4RqUAdRtyZg
gVItDHRXmXqBLaQpAgMBAAE=
-----END PUBLIC KEY-----`;
